spring:
  application:
    name: payment-api
  datasource:
    url: jdbc:postgresql://localhost:5432/payment_api
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
    #  jpa:
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
    # Spring Boot-specific; less flexible
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
