spring:
  application:
    name: payment-api
  datasource:
    url: jdbc:postgresql://localhost:5432/payment_api
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

#  jpa:
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
    # Spring Boot-specific; less flexible